//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.19408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
		
		public class WaypointTimeLong : MonoBehaviour 
		{
			public float waitTime = 6f;
			public Vector3 rotation = new Vector3(999, 999, 999);
			private Vector3 defaultRotation = new Vector3(999, 999, 999);
		}

		


